# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
#
# This base image is based on debian:buster-slim and contains:
#  * gcc 8.3.0
#  * clang 7.0.1
#  * cmake 3.13.4
#  * and more
#
# For details see https://github.com/ska-telescope/cpp_build_base
#
image: nexus.engageska-portugal.pt/ska-docker/cpp_build_base

variables:
  # Needed if you want automatic submodule checkout
  # For details see https://docs.gitlab.com/ee/ci/yaml/README.html#git-submodule-strategy
  GIT_SUBMODULE_STRATEGY: recursive

.src_dir_ref_storage: &src_dir_ref_storage
  - mkdir build || true
  - pwd > build/original_source_directory

.src_dir_ref_replacement: &src_dir_ref_replacement
  - old_sdir=`cat build/original_source_directory`
  - this_sdir=`pwd`
  - find build
    -type f -a
    \! \(
      -perm /111 -o
      \(
        -name '*.o' -o -name '*.a' -o -name '*.so'
      \)
    \)
    -exec sed -i "s|$old_sdir|$this_sdir|g" {} +

.common: {tags: [engageska, docker]}

.common.artifact-builder:
  extends: .common
  before_script:
    - *src_dir_ref_storage
  artifacts:
    paths:
      - build

.common.artifact-retriever:
  extends: .common
  before_script:
    - *src_dir_ref_replacement

stages:
  - build
  - linting
  - test
  - pages

build_debug:
  extends: .common.artifact-builder
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-coverage" -DCMAKE_EXE_LINKER_FLAGS="-coverage"
    - make

build_release:
  extends: .common.artifact-builder
  stage: build
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make

build_export_compile_commands:
 extends: .common.artifact-builder
 stage: build
 script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=clang++

lint_clang_tidy:
  extends: .common.artifact-retriever
  stage: linting
  needs: ["build_export_compile_commands"]
  script:
    - cd build
    - run-clang-tidy -checks='cppcoreguidelines-*,performance-*,readibility-*,modernize-*,misc-*,clang-analyzer-*,google-*'

lint_iwyu:
  extends: .common.artifact-retriever
  stage: linting
  needs: ["build_export_compile_commands"]
  script:
    - cd build
    - iwyu_tool -p .

lint_cppcheck:
  extends: .common.artifact-retriever
  stage: linting
  needs: ["build_export_compile_commands"]
  script:
    - cd build
    - cppcheck --error-exitcode=1 --project=compile_commands.json -q --std=c++14 -i $PWD/../resources -i $PWD/../src/ska/helloworld/test

test:
  extends: .common.artifact-retriever
  stage: test
  needs: ["build_debug"]
  script:
    - cd build
    - ctest -T test --no-compress-output
  after_script:
    - *src_dir_ref_storage
    - cd build
    - ctest2junit > ctest.xml
  artifacts:
    paths:
      - build/
    reports:
      junit: build/ctest.xml

test_installation:
  extends: .common.artifact-retriever
  stage: test
  needs: ["build_release"]
  script:
    - cd build
    - cmake . -DCMAKE_INSTALL_PREFIX=/opt
    - make install
    - cd ../src/examples/helloworld-user
    - if [ -d build ]; then rm -rf build; fi
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_PREFIX_PATH=/opt
    - make all

test_as_subproject:
  extends: .common.artifact-retriever
  stage: test
  script:
    - cp -r src/examples/helloworld-user ..
    - cd ../helloworld-user
    - sed -i 's/find_package(HelloWorld)/add_subdirectory(..\/ska-cpp-template helloworld EXCLUDE_FROM_ALL)/' CMakeLists.txt
    - if [ -d build ]; then rm -rf build; fi
    - mkdir build
    - cd build
    - cmake ..
    - make all

# A job that runs the tests under valgrid
# It might take a while, so not always run by default
test_memcheck:
  extends: .common
  stage: test
  needs: ["build_debug"]
  before_script:
    - *src_dir_ref_replacement
    - apt update && apt install -y valgrind
  script:
    - cd build
    - ctest -T memcheck
  only:
    - tags
    - schedules

pages:
  extends: .common
  stage: pages
  needs: ["test"]
  before_script:
    - *src_dir_ref_replacement
    - apt update && apt install -y curl
  script:
    - mkdir -p .public/build/reports
    - cd .public
    - gcovr -r ../ -e '.*/resources/.*' -e '.*/CompilerIdCXX/.*' -e '.*/tests/.*' --html --html-details -o index.html
    - gcovr -r ../ -e '.*/resources/.*' -e '.*/CompilerIdCXX/.*' -e '.*/tests/.*' --xml -o build/reports/code-coverage.xml
    - cp ../build/ctest.xml build/reports/unit-tests.xml
    # Create and upload GitLab badges
    - python ../.produce-ci-metrics.py build/reports > ci-metrics.json
    - curl -s https://gitlab.com/ska-telescope/ska-cicd-ci-metrics-utilities/raw/master/ska_ci_metrics_utilities/ci-badges-func.sh | sh
    - cd ..
    - mv .public public
  artifacts:
    paths:
      - public
